### ISSUE TITLE
Looks incredible!

### ISSUE THREAD

**Issue by ighellache** [fac26/Week6-GLNDK-Full-Stack-App#31]
I love the CSS! Little tip: the comics don't all fit onto the page, some overlap into the edge when the browser is resized.

Also the background doesn't fit onto the entire page when resized.

**Comment by nataliarusu** [comment]
<img width="894" alt="Screenshot 2023-02-22 at 17 21 24" src="https://user-images.githubusercontent.com/52968580/220707456-af418628-1324-4197-a56d-138949700c2a.png">

**Comment by Psydwinder** [comment]
Hey Iman and Natalia, 

Thanks for pointing this out, this has now been sorted 😃
