### ISSUE TITLE
LocalStorage/add to cart fix

### ISSUE THREAD

**Issue by modanova** [fac26/Week6-GLNDK-Full-Stack-App#41]
Firstly, thanks to @DominicSimpson for bearing with us when we were trying to solve this. 

The localStorage code you wrote seems to work. 

You'd need to enable it back by uncommenting the localStorage code here
https://github.com/fac26/Week6-GLNDK-Full-Stack-App/blob/152a732b9b3f85bd583f0534dba785fd05e48332/components/addToCart.js#L13-L15

Then set initial useState value to {}

``` javascript
const [item, setItem] = useState({});
```

But most importantly - clear your local storage. To do this go to your browser's console and type:

``` javascript
localStorage.clear()
```

Hope this helps! ✨

**Comment by konstantinakatmada** [comment]
thank you so much, Manoela 🥳  promised and delivered! Dom has already pushed some changes to the remote branch
